[web]
  title = "Surface RedwoodTemplate"
  port = 8910
  apiUrl = "${REDWOOD_API_URL:/.redwood/functions}"
  includeEnvironmentVariables = ["SUPABASE_URL","SUPABASE_KEY"]
[api]
  port = 8911
[browser]
  open = true
[datasets]
  organization = "SurfaceData"
  apiUrl = "https://catalog.api.surfacedata.org"
  homepage = "https://www.surfacedata.org"
